apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
  labels:
    provider: cassandra
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      name: cassandra
      labels:
        provider: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra
        ports:
        - containerPort: 7000
        - containerPort: 7001
        - containerPort: 7199
        - containerPort: 9042
        - containerPort: 9160
