apiVersion: v1
kind: Pod
metadata:
  name: {{.Chart.Name}}
spec:
  restartPolicy: {{default "Never" .restart_policy}}
  containers:
  - name: {{.container_name}}
    image: "alpine:3.3"
    command: ["/bin/sleep","9000"]
