apiVersion: v1
kind: Pod
metadata:
  name: {{.Chart.Name}}
  labels:
    heritage: helm
spec:
  restartPolicy: Never
  containers:
  - name: {{.container_name}}
    image: "alpine:3.2"
    command: ["/bin/sleep","9000"]
